# Generated by Django 5.2.5 on 2025-08-23 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_listings', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('new_messages', models.PositiveIntegerField(default=0)),
                ('new_reports', models.PositiveIntegerField(default=0)),
                ('search_terms', models.JSONField(default=dict, help_text='Popular search terms with their frequency')),
                ('top_models', models.JSONField(default=dict, help_text='Most viewed car models with their view counts')),
                ('popular_locations', models.JSONField(default=dict, help_text='Popular listing locations with counts')),
                ('revenue_data', models.JSONField(blank=True, default=dict, help_text='Revenue metrics if applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'db_table': 'analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_date_f1f7af_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'db_table': 'search_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='search_log_timesta_c9d421_idx'), models.Index(fields=['query'], name='search_log_query_8d8a06_idx')],
            },
        ),
    ]
