# Generated by Django 5.2.5 on 2025-08-23 16:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in kilometers')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('engine_size', models.CharField(help_text="e.g., '1.8L', '2.0L'", max_length=20)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'car',
                'indexes': [models.Index(fields=['make', 'model'], name='car_make_9d8b4a_idx'), models.Index(fields=['year'], name='car_year_af7265_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='available', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cars.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Listing',
                'verbose_name_plural': 'Car Listings',
                'db_table': 'car_listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cars.carlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'db_table': 'favorite',
            },
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['status'], name='car_listing_status_6b4f59_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['price'], name='car_listing_price_08650a_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['created_at'], name='car_listing_created_22461c_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['location'], name='car_listing_locatio_683ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='favorite_user_id_b99731_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'listing')},
        ),
    ]
