# Generated by Django 5.2.5 on 2025-08-23 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(blank=True, help_text='Optional: message related to a specific listing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cars.carlisting')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sender', 'timestamp'], name='message_sender__36eed7_idx'), models.Index(fields=['receiver', 'timestamp'], name='message_receive_6a0189_idx'), models.Index(fields=['listing'], name='message_listing_04b352_idx'), models.Index(fields=['is_read'], name='message_is_read_8eefe1_idx')],
            },
        ),
    ]
